[package]
name = "tun2"
version = "1.0.1"
edition = "2021"

authors = ["meh. <meh@schizofreni.co>", "@ssrlive"]
license = "WTFPL"

description = "TUN device creation and handling."
repository = "https://github.com/ssrlive/rust-tun"
keywords = ["tun", "network", "tunnel", "bindings"]

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
bytes = { version = "1" }
futures-core = { version = "0.3", optional = true }
libc = "0.2"
log = "0.4"
thiserror = "1"
tokio = { version = "1", features = [
    "net",
    "macros",
    "io-util",
], optional = true }
tokio-util = { version = "0.7", features = ["codec"], optional = true }

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "android"))'.dependencies]
ioctl = { version = "0.8", package = "ioctl-sys" }

[target.'cfg(target_os = "windows")'.dependencies]
wintun = { version = "0.4", features = ["panic_on_unsent_packets"] }

[dev-dependencies]
ctrlc2 = { version = "3.5", features = ["tokio", "termination"] }
futures = "0.3"
packet = "0.1"
tokio = { version = "1", features = ["rt-multi-thread"] }

[features]
default = []
async = ["tokio", "futures-core", "tokio-util"]

[[example]]
name = "read-async"
required-features = ["async"]

[[example]]
name = "read-async-codec"
required-features = ["async"]

[[example]]
name = "ping-tun"
required-features = ["async"]
